name: node_project
on:
  push:
    branches:
      - main
      - dev
  pull:
    branches:
      - main
      - release-*

jobs:
  test:
    runs-on: ubuntu: latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npn-ci
      - name: run test
        run: npm test

  deploy:
    needs: test
    run-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npn-ci
      - name: build project
        run: npm run build
      - name: deploy
        run: echo "deploying the application"



